export const Config = {
  PORT: Number(process.env.PORT ?? 3001),
  SEAT_COUNT: 5,
  MIN_BET: 10,
  MAX_BET: 500,
  STARTING_BANKROLL: 1000,
  SHOE_DECKS: 6,
  CUT_CARD_POSITION_RATIO: 0.25,
  DEALER_STANDS_ON_SOFT_17: true,
  DOUBLE_AFTER_SPLIT: true,
  RESPLIT_ACES: false,
  BLACKJACK_PAYOUT_NUMERATOR: 3,
  BLACKJACK_PAYOUT_DENOMINATOR: 2,
  DISCONNECT_GRACE_MS: 30_000,
  ROOM_CODE_LENGTH: 5,
  SETTLE_PAUSE_MS: 3_000,
  BET_DEADLINE_MS: 10_000,
  DEALING_DURATION_MS: 2_000,  // CHANGED from 1_500. Must be >= the longest possible client deal animation: (nonEmptyPlayerCount + 1) * client DEAL_CARD_INTERVAL_MS + CARD_ENTRY_DURATION_S. See client/src/lib/animation-timings.ts.
  DB_PATH: process.env.DB_PATH ?? 'data/blackjack.db',
} as const;
